import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App'
import { registerSW } from 'virtual:pwa-register'

// Register the Workbox service worker generated by vite-plugin-pwa.
// `registerType: 'prompt'` means the new SW waits in `waiting` state until we
// call updateSW(); we do that here after showing a non-blocking toast so users
// are never silently served a stale bundle.
const updateSW = registerSW({
  onNeedRefresh() {
    // Show a simple browser confirm so we don't need a dedicated Toast
    // component at this layer. In a future iteration this can be wired into the
    // Zustand notification store and shown as an in-app banner.
    if (window.confirm('A new version of Stratum is available. Reload to update?')) {
      void updateSW(true)
    }
  },
  onOfflineReady() {
    // The app shell is cached and ready for offline use.
    // Silent — no UI feedback needed for the initial cache warm.
  },
})

const rootEl = document.getElementById('root')
if (!rootEl) throw new Error('Root element not found')

createRoot(rootEl).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
